ckpt_root: ckpt
cuda: True
num_workers: 2

dataset:
    name: 'CoughDataset'
    #common_kwargs:
            #image_size: (2048, 2048)
    train_kwargs:
        transform: 'train'
        txt: '/home/ubuntu/COVID19-cough-classification/lib/dataset/train.txt'   
    valid_kwargs:
        transform: 'valid'
        txt: '/home/ubuntu/COVID19-cough-classification/lib/dataset/valid.txt'
        #test_kwargs:
        #transform: 'test'
        #txt: '/home/ubuntu/COVID19-cough-classification/lib/dataset/test.txt'
training:
    optim: Adam
    epoch: 500
    batch_size: 256
    save_every: 5
    lr: 0.001
    weight_decay: 0.001


model:
    file: lib.model.CoughModel
    modelclass: CoughModel
    loss_func: 'CrossEntropyLoss'

testing:
    batch_size: 1
    ckpt_root: 'ckpt'
